# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-Visual
version:      0.07
version_from: Visual.pm
installdirs:  site
requires:
    Curses:                        
    POE:                           0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
